version: '3.3'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_DB=api_express_docker
      - POSTGRES_USER=cristian
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgress_data:/var/lib/postgressql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
    depends_on:
      - postgres

  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=api_express_docker
      - MYSQL_USER=cristian
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_PORT=3306
    ports:
      - 3306:3306

    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin 
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - PMA_HOST=mysql
    ports:
      - 8080:80
